### ISSUE TITLE
Error returned by R base function during CliRLimmaTest

### ISSUE THREAD

**Issue by benjasriga** [dfci-cccb/mev#972]
My attempt to install fails at the testing stage CliRLimmaTest because of a call to the colnames base function. I am using R 3.1.1 with limma_3.22.7. I know your README said R 2.15. If you have no plans for implementing newer versions in the foreseeable future, I will go ahead and install an instance of 2.15 on my machine to see if that resolves the issue.

### This is the error I get
Standard error:
Loading required package: methods
Warning message:
package ‘limma’ was built under R version 3.1.3 
Error in `colnames<-`(`*tmp*`, value = c("ID", "Log Fold Change", "Average Expression",  : 
  'names' attribute [7] must be the same length as the vector [6]
Execution halted
###

I think you are trying to assign a name to a column that doesn't exist (at least from my version of limma). The gene symbol "ID" is not a column of the data frame returned by topTable, but the corresponding row name. Hence the error. 
## reassign colnames
colnames(result)=c("ID", "Log Fold Change", "Average Expression", "t", "P-value", "q-value", "B")

**Comment by jfarid27** [comment]
Can you tell us what system you're trying to install on? If your system is *nix based, symbolic link R and Rscript to versions 2.15 in a folder that's available to your $PATH. The system won't run without 2.15 due to version controlling bioconductor packages. Only >3 is necessary to run a separate R server for Non-negative matrix factorization for now. 

Also, you can [try R on our installation](http://mev.tm4.org/#/welcome) if you just want to upload data and get started. Keep us updated if you run into trouble still.

**Comment by lev-kuznetsov** [comment]
We're in the process of changing our R integration, some analyses require older version of R. If you don't wish to install older version of R you can skip maven tests with `mvn -DskipTests install` but those analyses will cause errors. We're working on fixing these
